CREATE DATABASE IF NOT EXISTS `todo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `todo`;

CREATE TABLE IF NOT EXISTS `todos` (
  `id` bigint NOT NULL PRIMARY KEY AUTO_INCREMENT ,
  `content` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
